version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "npm"
      - "dependencies"
      - "maintenance"
    # Only create PRs for security updates
    open-pull-requests-limit: 0
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    # Only create PRs for security updates
    open-pull-requests-limit: 0
    labels:
      - "ruby"
      - "dependencies"
      - "maintenance"
